---
# tasks file for sonarr
  - name: Add sonarr/ key
    apt_key:
      keyserver: '{{ item.server }}'
      id:        '{{ item.id }}'
    with_items:
      - { server: 'hkp://keyserver.ubuntu.com:80', id: '3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF' }
      - { server: 'keyserver.ubuntu.com',          id: 'D9B78493' }

## add the repos
  - name: Add repos required for sonarr
    apt_repository:
      repo: '{{ item }}'
      state: present
      update_cache: yes
    with_items:
      - deb http://download.mono-project.com/repo/debian wheezy main
      - deb http://apt.sonarr.tv/ master main

  - name: Install Mono and Sonarr
    apt:
      name: '{{ item }}'
      update_cache: yes
    with_items:
      - mono-devel
      - nzbdrone

  - name: Copy nzbdrone config and service files
    copy:
      src:   '{{ item.src   }}'
      dest:  '{{ item.dest  }}'
      owner: '{{ item.owner  }}'
      group: '{{ item.group }}'
      mode:  '{{ item.mode  }}'
    with_items:
      - { src: 'roles/sonarr/files/NzbDrone_config/', dest: '/home/vagrant/.config/NzbDrone/', owner: 'vagrant', group: 'vagrant', mode: '0644' }
      - { src: 'roles/sonarr/files/nzbdrone',         dest: '/etc/init.d/',                    owner: 'root',    group: 'root',    mode: '0755' }
    notify: nzbdrone service
