---
# tasks file for java8
  - name: Add repos required for oracle java8
    apt_repository:
      repo: ppa:webupd8team/java
      state: present
      update_cache: yes
  - name: Install debconf-utils
    apt:
      name: debconf-utils
      cache_valid_time: 3600
  - shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: Install Oracla Java 8
    apt:
      name: oracle-java8-installer
      cache_valid_time: 3600
