---
# tasks file for elasticsearch
  - name: Add elasticsearch key
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present
    tags:
      - elasticsearch_key

  - name: Add repos required for elasticsearch
    apt_repository:
      repo: deb http://packages.elastic.co/elasticsearch/2.x/debian stable main
      state: present

  - name: Install elasticsearch and unzip
    apt:
      name: '{{ item }}'
      update_cache: yes
    with_items:
      - elasticsearch
      - unzip

  - name: Set server host ip
    replace:
      dest: /etc/elasticsearch/elasticsearch.yml
      regexp: '^# network\.host.*'
      replace: 'network.host: ["{{ ansible_eth1["ipv4"]["address"]}}", "localhost"]'

  - name: Start elasticsearch service
    service:
      name: elasticsearch
      state: started
      enabled: yes

  - name: Ensure consul dir exists
    file:
      path: /etc/consul.d
      state: directory

  - name: Template elasticsearch consul file
    template:
      src: roles/elasticsearch/templates/elasticsearch_consul.json
      dest: /etc/consul.d/

  - name: Get the dashboards archive and filebeat index template
    get_url:
      url:  '{{ item }}'
      dest: /home/vagrant/
    with_items:
      - https://download.elastic.co/beats/dashboards/beats-dashboards-1.1.0.zip
      - https://gist.githubusercontent.com/thisismitch/3429023e8438cc25b86c/raw/d8c479e2a1adcea8b1fe86570e42abab0f10f364/filebeat-index-template.json

  - name: Uncompress the archive
    unarchive:
      src: /home/vagrant/beats-dashboards-1.1.0.zip
      dest: /home/vagrant/
      copy: no

  - name: Load the dashboards
    command: ./load.sh
    args:
      chdir: /home/vagrant/beats-dashboards-1.1.0

  - name: Load filebeat index template
    shell: "curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@filebeat-index-template.json"
