---

  - hosts: elasticsearch_server
    roles:
      - { role: elasticsearch, become: True}

  - hosts: logstash_server
    roles:
      - { role: logstash, become: True}

  - hosts: kibana_server
    roles:
      - { role: kibana, become: True}
      - { role: nginx, become: True}

  - hosts: consul
    roles:
      - { role: consul, become: True}
