# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "logstash" do |logstash|
    logstash.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.101"
    ssh_pub_key = File.readlines("./ssh/id_rsa.pub").first.strip
    logstash.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "elasticsearch" do |elasticsearch|
    elasticsearch.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.102"
    ssh_pub_key = File.readlines("./ssh/id_rsa.pub").first.strip
    elasticsearch.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "kibana" do |kibana|
    kibana.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.103"
    ssh_pub_key = File.readlines("./ssh/id_rsa.pub").first.strip
    kibana.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "filebeat" do |filebeat|
    filebeat.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.104"
    ssh_pub_key = File.readlines("./ssh/id_rsa.pub").first.strip
    filebeat.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
     vb.customize ["modifyvm", :id, "--cpus", "1"]
     # Customize the amount of memory on the VM:
     vb.memory = "512"
  end

end
